### ISSUE TITLE
Email Template for Login

### ISSUE THREAD

**Issue by jishnud17** [Allen-ISD-Computer-Science/IRL_DutySchedule_2024#2]

**Comment by Muq2** [comment]
Template: forgot password
Subject: ACTION REQUIRED: Forgotten Password for Duty Dashboard Account
Body: 
Dear #(user),

Looks like you have forgotten your password, please click <a href="forgotpassword/#(token)">this link</a> to reset your password.

If you did not make such a request, please disregard this email.

Kindest regards,
Duty Dashboard Team

------------------------------------------------------------------------------------------------------

Template: verify account
Subject: ACTION REQUIRED: Verify Account for Duty Dashboard
Body: 
Dear #(user),

In order to verify your account for the AHS Model Scheduler, please click <a href="verify/#(token)">this link</a>.

If you did not make such a request, please disregard this email.

Kindest regards,
Duty Dashboard Team

**Comment by CSAllenISD** [comment]
Completed
